## Introduction to Numpy

#### **Name:** Adiel Nefthali Delgado Silva


#### Import numpy

In [1]:
import numpy as np

#### Numpy operations
1.- Create array a with values from 1-5 \
2.- create an array b with values from 6 - 10

In [5]:
a = np.arange(1,6)
b = np.arange(6,11)

In [7]:

lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [6]:
lista = [i for i in range(1,6)]
lista

[1, 2, 3, 4, 5]

#### Matrix Operations with numpy

1. Create a 3x3 matrix in numpy with the following values: 

⎡ 1  2  3 ⎤ \
⎢ 4  5  6 ⎥ \
⎣ 7  8  9 ⎦ 

2.- Transpose the matrix and save it into a transpose variable \
3.- Add both matrix \
4.- Multiply both matrix



1.-

In [12]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2.-


In [13]:
Transpose = matrix.T
Transpose
#Shape te dice los valores que contiene el array, tipo cuantas filas y columnas tiene
#Transpose.shape


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

3.-

In [14]:
sum = matrix + Transpose
sum

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

4.-

In [15]:
multi = matrix @ Transpose
multi

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

#### numpy indexing

1.- Create a numpy array [10, 20, 30, 40, 50, 60] \
2.- print second and last index \
3.- print elements 1-3 \
4.- print all but the first 2 elements \
5.- reshape the array to be a 2x3 matrix 

1.-

In [16]:
arr = np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

2.-

In [17]:
arr[1]

np.int64(20)

In [18]:
arr[-1]

np.int64(60)

3.-

In [20]:
arr[0:3]

array([10, 20, 30])

4.-

In [21]:
arr[2:]

array([30, 40, 50, 60])

5.-

In [22]:
arr.reshape(2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

#### Creating random arrays
1- Create a 3x3 matrix with random numbers. \
2.- Create a 2x3 matrix with random integers.


1.-

In [23]:

random_array = np.random.rand(3,3)
random_array

array([[0.77736441, 0.8800917 , 0.62374608],
       [0.65974882, 0.02604283, 0.40942959],
       [0.10790198, 0.84073032, 0.03184002]])

2.-

In [24]:
random_array_int = np.random.randint(0,10, size=[3,3])
random_array_int

array([[7, 9, 2],
       [3, 7, 8],
       [8, 2, 7]], dtype=int32)

#### Boolean Indexing and Filtering
1.- Generate a random dataset in a 5x5 matrixs filled with integers from 1-50. \
2.- Filter the values that are bigger than 25 and replace them with 0. \
3.- Calculate the basic statisticañ dispersion and tendency meassurements.

1.-

In [25]:
dataset = np.random.randint(1,51, size=[5,5])
dataset

array([[49, 19, 17, 43, 24],
       [ 2, 15, 37, 39, 26],
       [ 6, 24, 33, 38, 20],
       [14, 35, 50,  4, 26],
       [43, 43, 42, 37, 37]], dtype=int32)

2.-

In [26]:
dataset[dataset > 25] = 0
dataset

array([[ 0, 19, 17,  0, 24],
       [ 2, 15,  0,  0,  0],
       [ 6, 24,  0,  0, 20],
       [14,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0]], dtype=int32)

3.-

In [27]:
np.std(dataset)

np.float64(8.574380444090407)

In [28]:
np.mean(dataset)

np.float64(5.8)

In [29]:
np.median(dataset)

np.float64(0.0)

In [30]:
np.var(dataset)

np.float64(73.52)

#### Homework exercise numpy

⎡ 2  3 ⎤ \
⎣ 0  1 ⎦ 


⎡ 1  2 ⎤  
⎣ 4  0 ⎦ 

1. The product
2. Product's transpose.
3. Determinant of the product
4. The inverse of the product.

1.-

In [ ]:
A = np.array([[2,3],[0,1]])
B = np.array([[1,2],[4,0]])

array([[1, 2],
       [4, 0]])

In [37]:
A*B

array([[2, 6],
       [0, 0]])

In [38]:
C = A@B
C

array([[14,  4],
       [ 4,  0]])

2.-

In [39]:
transpose = C.T
transpose

array([[14,  4],
       [ 4,  0]])

3.-

In [40]:
Determinante = np.linalg.det(C)
Determinante

np.float64(-15.999999999999998)

4.-

In [41]:
inverse = np.linalg.inv(C)
inverse

array([[ 0.   ,  0.25 ],
       [ 0.25 , -0.875]])